const cities: string[] = [
  "audubon",
  "barrington",
  "bellmawr",
  "berlin",
  "brooklawn",
  "cherry hill",
  "clementon",
  "collingswood",
  "deptford",
  "east greenwich",
  "elk",
  "franklin",
  "gibbsboro",
  "glassboro",
  "gloucester city",
  "gloucester township",
  "greenwich",
  "haddon heights",
  "haddonfield",
  "harrison",
  "hi-nella",
  "laurel springs",
  "lawnside",
  "lindenwold",
  "logan",
  "magnolia",
  "mantua",
  "merchantville",
  "monroe",
  "mount ephraim",
  "national park",
  "newfield",
  "oaklyn",
  "pine hill",
  "pine valley",
  "pitman",
  "runnemede",
  "somerdale",
  "south harrison",
  "stratford",
  "swedesboro",
  "tavistock",
  "voorhees",
  "washington",
  "wenonah",
  "west deptford",
  "westville",
  "winslow",
  "woodbury",
  "woodbury heights",
  "woolwich",
];

export default cities;
